#!/bin/bash

# Function : Help, Usage
usage() {
    echo "pkgs-installer"
    echo "usage: $0 package-name " >&2
    echo
    echo "packages supported:"
    echo "    apmm - apache, php, mariadb, postfix"
    echo "    ntp - ntp"
    echo "    optimize - optimize operating system"
    echo "    webmin - webmin"
    echo
    exit 0
}

# Function : Apmm
apmm() {
    echo "1"
    exit 0
    # Add repository
    # Apache2
    sudo add-apt-repository ppa:ondrej/apache2 -y
    # Mariadb
    sudo apt install software-properties-common dirmngr apt-transport-https curl -y
    sudo curl -o /etc/apt/trusted.gpg.d/mariadb_release_signing_key.asc 'https://mariadb.org/mariadb_release_signing_key.asc'
    sudo sh -c "echo 'deb https://tw1.mirror.blendbyte.net/mariadb/repo/10.10/ubuntu jammy main' >>/etc/apt/sources.list"
    # Php
    sudo add-apt-repository ppa:ondrej/php -y
    sudo apt update

    #Installing
    # sudo apt policy | grep "apache2"
    # sudo apt-cache showpkg apache2
    # sudo apt policy | grep "php"
    # sudo apt-cache showpkg php8.2
    # Apache2
    sudo apt install apache2=2.4.55-1+ubuntu22.04.1+deb.sury.org+2 -y; apachectl -v
    sudo a2enmod rewrite; a2enmod ssl; systemctl restart apache2;
    # MariaDB
    sudo apt install mariadb-server -y
    # PHP
    sudo apt install php8.2 -y; php -v;
    sudo apt install php8.2-{bz2,imagick,imap,intl,gd,mbstring,pspell,curl,readline,xml,xmlrpc,zip,mysql} -y
    # sudo apt list php8.2-*
    # Postfix
    # PHPMyAdmin
    cd /home; sudo apt install unzip; wget https://files.phpmyadmin.net/phpMyAdmin/5.2.0/phpMyAdmin-5.2.0-all-languages.zip
    unzip phpMyAdmin*; rm -rf phpMyAdmin*zip; mv phpMyAdmin* phpmyadmin;
    sudo sed -i "s/$cfg\['blowfish_secret'\] = ''/$cfg\['blowfish_secret'\] = 'sVJWUBG=L4XoCh6xD9=XXlVzjtQfZe0j'/g" /home/phpmyadmin/libraries/config.default.php
    mkdir /home/phpmyadmin/tmp; chmod 707 /home/phpmyadmin/tmp;

    # Default settings
    # Apache2
    sudo sed -i 's/ServerTokens OS/ServerTokens Prod/g' /etc/apache2/conf-enabled/security.conf
    sudo sed -i 's/ServerSignature On/ServerSignature Off/g' /etc/apache2/conf-enabled/security.conf
    sudo sed -i 's/Options Indexes FollowSymLinks/\# Options Indexes FollowSymLinks/g' /etc/apache2/apache2.conf
    sudo sed -i 's/Options FollowSymLinks/\# Options FollowSymLinks/g' /etc/apache2/apache2.conf
    echo "ServerName localhost" >> /etc/apache2/apache2.conf
    sudo sed -i'' -r -e "/Listen 443/a\Listen 8080" /etc/apache2/ports.conf
    mv /var/www/html/index.html /var/www/html/index.php
    echo '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"><html><head><title>200 HTTP OK</title></head><body><h1>HTTP OK</h1><p>The http server is running fine.</p></body></html>' > /var/www/html/index.php
    sudo systemctl restart apache2
}

# Function : Ntp
ntp() {
    sudo apt install ntp -y
    sudo systemctl restart ntp
    sudo ntpq -p
    sudo timedatectl set-timezone 'Asia/Seoul'
}

# Function : Optimize
optimize() {
    echo "Please enter your new root password(e.g. Abcd1234$):"
    sudo passwd root
    echo
    echo "Please enter your new hostname(system1):"
    read hostname
    sudo hostnamectl set-hostname $hostname
    echo
    echo "Update and upgrade your system:"
    sudo apt update; sudo apt upgrade -y;
}

# Function : Webmin
webmin() {
    wget -q http://www.webmin.com/jcameron-key.asc -O- | sudo apt-key add -
    sudo add-apt-repository "deb [arch=amd64] http://download.webmin.com/download/repository sarge contrib"
    sudo apt install webmin -y
}

case "$1" in
    -h|--help) usage; exit 0 ;;
    apmm) apmm; exit 0 ;;
    ntp) ntp; exit 0 ;;
    optimize) optimize; exit 0 ;;
    webmin) webmin; exit 0 ;;
    *) usage; exit 0 ;;
esac


# exit 0
# if (( $# >= 1 )); then
# else
#     usage; exit 0;
# fi
# exit 0